version: '3'
services:
  # HomeAssistant
  homeassistant:
    container_name: ${PROJECT_NAME}
    image: homeassistant/raspberrypi3-homeassistant:stable
    ports:
      - 8123:8123
    restart: unless-stopped
    volumes:
      # Local path where your home assistant config will be stored
      - ./volumes/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro

volumes:
  homeassistant:
