version: '3'
services:
  # HomeAssistant
  homeassistant:
    container_name: ${PROJECT_NAME}
    image: homeassistant/raspberrypi3-homeassistant:stable
    volumes:
      # Local path where your home assistant config will be stored
      - ./volumes/home-assistant/:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    user: "${UID}:${UID}"
